controller:
  replicaCount: 1
persistence:
  storageClass: "ebs-sc"

listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT

broker:
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: "ebs-sc"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true
